[project]
name = "emotion-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "kagglehub>=0.4.0",
    "matplotlib>=3.10.8",
    "opencv-python>=4.12.0.88",
    "tqdm>=4.67.1",
]
